### ISSUE TITLE
Set a theme?

### ISSUE THREAD

**Issue by dmurdoch** [steveush/foodoc#19]
The docs say that `foodoc` is derived from `docStrap`, and the config files look quite similar.  `docStrap` supports `bootswatch` themes using a `theme` entry.  `foodoc` has the `stylesheets` and `scripts` entries.  Are they sufficient to change themes?  Is there any guidance on how to do it?

**Comment by steveush** [comment]
Hey @dmurdoch,

Been a while since I've looked at this project, unfortunately there is no support for bootswatch themes. At the top of the README it says:

> This project began as a simple modification of DocStrap. **_Removing the Bootswatch support in favor of my own CSS customizations_** but it ended up with me re-writing pretty much the entire template, even switching out the template engine to Handlebars.

There is simple theming support using the **_systemColor_** and **_systemLogo_** options but other than that anything else will need to be done as a custom stylesheet and then included with the **_stylesheets_** option.

The stylesheets option doesn't do anything other than loop through the string array and dump the provided strings into the `<head/>` as stylesheets. You can see how it does it looking at the [_layout.hbs file](https://github.com/steveush/foodoc/blob/master/src/tmpl/site/_layout.hbs#L18) in the repo. So if you want to provide custom CSS you can write your stylesheet and call it say `custom.css`. Then when you generate the template set the `stylesheets` option to be `stylesheets: ["css/custom.css"]`. Once the template is generated you can then copy your `custom.css` file into the `css` folder along with the other CSS files and it should be good to go.

Thanks

**Comment by dmurdoch** [comment]
Thanks for the detailed response!
